nome = str(input('Digite seu nome: ')).strip()
print('ANALISANDO SEU NOME...')
print(f'Seu nome escrito em letras maiúsculas é {nome.upper()}.')
print(f'Seu nome escrito em letras minúsculas é {nome.lower()}.')
print(f'Seu nome completo tem ao todo {len(nome) - nome.count(' ')} letras.')
#print(f'Seu primeiro nome tem {nome.find(' ')} letras.')
separa = nome.split()
print(f'Seu primeiro nome é {separa[0]} e ele tem {len(separa[0])} letras.')
