a = input('Digite algo: ')
print(f'O tipo primitivo de {a} é {type(a)}')
print('Só tem espaços?:', a.isspace())
print('É um número?:', a.isnumeric())
print('É alfabético?:', a.isalpha())
print('É alfanumérico?:', a.isalnum())
print('Esta em maíusculo?:', a.isupper())
print('Esta em minúsculo?:', a.islower())
print('Está capitalizada?:', a.istitle())
